/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.javaproject;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *  
 * @author thong
 */
public class AsignTechnician extends javax.swing.JPanel {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Login Frame");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.getContentPane().add(new AsignTechnician()); // Instantiate and add your login panel
            frame.pack();
            frame.setVisible(true);
        });
    }
    /**
     * Creates new form FeedbackManagement
     */
    private JFrame frame; // Instance variable to hold the reference to the frame

    
    public AsignTechnician() {
        initComponents();
        populateTable();
    }

    
    public void populateTable(){
        String columns [] = {"Name","status","solving","Phone Number","date"};
        String data [][] = {{"John Doe","free","none","123-456-7890","2024-03-20",},
                            

    };
        DefaultTableModel model = new DefaultTableModel(data,columns);
        jTable1.setModel(model);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Select_technician = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Assign task");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Asign Technician");

        Select_technician.setText("Select technician");
        Select_technician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select_technicianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(Select_technician)
                        .addGap(53, 53, 53)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Select_technician))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Select_technicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select_technicianActionPerformed
       // Get the selected row index
    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow != -1) { // Ensure a row is selected
        // Extract data from the selected row
        String name = jTable1.getValueAt(selectedRow, 0).toString();
        String roomNumber = jTable1.getValueAt(selectedRow, 1).toString();
        String phoneNumber = jTable1.getValueAt(selectedRow, 3).toString();
        String date = jTable1.getValueAt(selectedRow, 4).toString();
        
        // Show a message indicating the selected problem
        String message = "You have selected the following problem:\n\n"
                         + "Name: " + name + "\n"
                         + "Room Number: " + roomNumber + "\n"
                         + "Phone Number: " + phoneNumber + "\n"
                         + "Date: " + date + "\n";
        JOptionPane.showMessageDialog(this, message, "Selected Problem", JOptionPane.INFORMATION_MESSAGE);
    } else {
        // If no row is selected, show an error message
        JOptionPane.showMessageDialog(this, "Please select a task to assign.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Select_technicianActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Get the selected row index
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow != -1) { // Ensure a row is selected
            // Proceed with task assignment
            TaskAssigned newpage = new TaskAssigned();

            // Get the JFrame containing this panel
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);

            // Replace current panel with the task assigned panel
            frame.getContentPane().removeAll(); // Remove all components from the frame
            frame.getContentPane().add(newpage); // Add task assigned panel
            frame.pack(); // Resize frame to fit the new panel
        } else {
            // If no row is selected, show a message
            JOptionPane.showMessageDialog(this, "Please select a technician.", "No Problem Selected", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Select_technician;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
