/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.javaproject;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author thong
 */
public class welcome2 extends javax.swing.JPanel {
    public static void main(String[] args){
        JFrame frame = new JFrame("Welcome Frame");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new welcome2());
        frame.pack();
        frame.setVisible(true);
    }
    /**
     * Creates new form welcome2
     */
    public welcome2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previous = new javax.swing.JButton();
        NextPage = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        previous.setText("previous");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        NextPage.setText("Next");
        NextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextPageActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Welcome to second page");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(previous)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NextPage)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previous)
                    .addComponent(NextPage))
                .addGap(85, 85, 85))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextPageActionPerformed
        // TODO add your handling code here:
        
    welcome newpage = new welcome();
    
    // Get the JFrame containing this panel
    JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
    
    // Replace current panel with welcome2 panel
    frame.getContentPane().removeAll(); // Remove all components from the frame
    frame.getContentPane().add(newpage); // Add welcome2 panel
    frame.pack(); // Resize frame to fit the new panel
    }//GEN-LAST:event_NextPageActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        // TODO add your handling code here:
                
    welcome newpage = new welcome();
    
    // Get the JFrame containing this panel
    JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
    
    // Replace current panel with welcome2 panel
    frame.getContentPane().removeAll(); // Remove all components from the frame
    frame.getContentPane().add(newpage); // Add welcome2 panel
    frame.pack(); // Resize frame to fit the new panel
    }//GEN-LAST:event_previousActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextPage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton previous;
    // End of variables declaration//GEN-END:variables
}
