/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.javaproject;
import javax.swing.*;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author thong
 */

public class typyUser extends javax.swing.JPanel {
    public static void main(String[] args){
        JFrame frame = new JFrame("Welcome Frame");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new typyUser());
        frame.pack();
        frame.setVisible(true);
    }
    /**
     * Creates new form typyUser
     */
    public typyUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        technician = new javax.swing.JButton();
        management = new javax.swing.JButton();

        technician.setText("technician");
        technician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technicianActionPerformed(evt);
            }
        });

        management.setText("management");
        management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(management, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(technician, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(technician, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(management, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void technicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technicianActionPerformed
    Techlogin newpage = new Techlogin();
    
    // Get the JFrame containing this panel
    JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
    
    // Replace current panel with welcome2 panel
    frame.getContentPane().removeAll(); // Remove all components from the frame
    frame.getContentPane().add(newpage); // Add welcome2 panel
    frame.pack(); // Resize frame to fit the new panel
    }//GEN-LAST:event_technicianActionPerformed

    private void managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managementActionPerformed
        // TODO add your handling code here:
    ManagementLogin newpage = new ManagementLogin();
    
    // Get the JFrame containing this panel
    JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
    
    // Replace current panel with welcome2 panel
    frame.getContentPane().removeAll(); // Remove all components from the frame
    frame.getContentPane().add(newpage); // Add welcome2 panel
    frame.pack(); // Resize frame to fit the new panel
        
    }//GEN-LAST:event_managementActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton management;
    private javax.swing.JButton technician;
    // End of variables declaration//GEN-END:variables
}
